mqttbroker:
    image: toke/mosquitto
    env_file: .env
    ports:
        - "1883:1883"
app:
    build: .
    command: './gonna_meet_you_halfway_golang'
    ports:
        - '8080:8080'
    env_file: .env
    container_name: 'halfway'
    links: 
        - mqttbroker
